#ifndef __LIBSPL_TZS_H__
#define __LIBSPL_TZS_H__

enum SPLTZ_MODINFO_ENTS {
    SPLTZ_MODINFO_INTRMGR = 0,
    SPLTZ_MODINFO_SYSMEM,
    SPLTZ_MODINFO_EXCPMGR,
    SPLTZ_MODINFO_BUSERR,
    SPLTZ_MODINFO_SMSCHED,
    SPLTZ_MODINFO_DRVR,
    SPLTZ_MODINFO__COUNT
};

enum SPLTZ_SMCS {
    SPLTZ_SMC_RET0 = 0x80,
    SPLTZ_SMC_WRITE32P,
    SPLTZ_SMC_READ32P,
    SPLTZ_SMC__COUNT
};

#endif // __LIBSPL_TZS_H__